### ISSUE TITLE
Viewer Error when running build_city_and_meshes.py on Windows

### ISSUE THREAD

**Issue by Georspai** [dtcc-platform/dtcc-viewer#9]
When running  `build_city_and_meshes.py` demo on Windows 10 we get an error on `volume_mesh_boundary.view()`. All the other `.view()` functions work. 

This is the full error message:  
```
INFO: No valid colors found embeded in mesh object with name: Mesh
Coloring per vertex z-value
dict_keys([<class 'numpy.ndarray'>, <class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'ctypes.c_void_p'>])
dict_keys([<class 'numpy.ndarray'>, <class 'bytes'>, <class 'OpenGL.converters.c_long_Array_1'>, <class 'ctypes.c_void_p'>])
Traceback (most recent call last):
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\wrapper.py", line 668, in wrapperCall
    cArgs = tuple(calculate_cArgs( pyArgs ))
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\wrapper.py", line 471, in calculate_cArgs
    yield converter( pyArgs, index, self )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\converters.py", line 252, in __call__
    return self.arrayType.asArray( pyArgs[index] )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: 1) registered', 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x000001DA7A252040>', (1, 1), 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x000001DA7A2DE780>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\George\Documents\build_city_and_meshes.py", line 46, in <module>
    volume_mesh_boundary.view()
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dtcc_viewer\mesh_opengl.py", line 45, in view
    window.render(scene)
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dtcc_viewer\opengl_viewer\window.py", line 152, in render
    mesh_gl = MeshGL(mesh)
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dtcc_viewer\opengl_viewer\mesh_gl.py", line 238, in __init__
    self._create_shadow_map()
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dtcc_viewer\opengl_viewer\mesh_gl.py", line 331, in _create_shadow_map
    glGenTextures(1, self.FBO)
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\wrapper.py", line 668, in wrapperCall
    cArgs = tuple(calculate_cArgs( pyArgs ))
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\wrapper.py", line 471, in calculate_cArgs
    yield converter( pyArgs, index, self )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\converters.py", line 252, in __call__
    return self.arrayType.asArray( pyArgs[index] )
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\arrays\arraydatatype.py", line 171, in asArray
    return cls.getHandler(value).asArray(value, typeCode or cls.typeConstant)
  File "C:\Users\George\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\OpenGL\arrays\arraydatatype.py", line 59, in __call__
    raise TypeError(
TypeError: ('No array-type handler for type numpy.uintc (value: 1) registered', 'Failure in cConverter <OpenGL.converters.SizedOutputOrInput object at 0x000001DA7A252040>', (1, 1), 1, <OpenGL.platform.baseplatform.glGenTextures object at 0x000001DA7A2DE780>)
```

**Comment by dwastberg** [comment]
Likely related to this issue
https://stackoverflow.com/questions/76155091/np-uint32-np-uintc-on-windows
